//Configurações do Supabase
export const SUPABASE_URL = "https://rjmwkoqbeaaehaumzcjj.supabase.co"
export const API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJqbXdrb3FiZWFhZWhhdW16Y2pqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk4NDAzMjYsImV4cCI6MjA3NTQxNjMyNn0.7WOu6MAKPbqnNLuFMSXm-a2KW8qulbqlh_JW7FqcRZE"